[[https://travis-ci.org/mkaito/cad-inf-ped2][file:https://travis-ci.org/mkaito/cad-inf-ped2.svg?branch=master]]

* PED2
Curso de Acceso Directo 2018/19.

Fundamentos de la Informática.

Prueba de Evaluación a Distancia 2.

Vea el enunciado [[file:PED2.pdf][aqui]].

** Dependencias de sistema.
Si usa usted [[https://nixos.org/nix/][Nix]], tan solo deberá abrir una =nix-shell=, que contendrá todas las
dependencias necesarias.

De lo contrario:

- Será necesario una distribución de [[https://rustup.rs/][Rust]].
- Bajo Windows, necesitará también VS 2012, VS 2015, o VS 2017, con el componente VSC++ instalado.
- Bajo macOS, necesitará la herramienta XCode.

** Instrucciones de compilación
Este repositorio contiene un proyecto Cargo con dos ejecutables:

- =hola=
- =numero_mayor=

Para compilar estos ejecutables:

#+BEGIN_SRC
❯ cargo build
#+END_SRC

Tras lo cual, los ejecutables se encuentran en el directorio =target/debug=.

Puede compilar y ejecutar al mismo tiempo:

#+BEGIN_SRC
❯ cargo run --bin hola
❯ cargo run --bin numero_mayor
#+END_SRC

** Sesiones de ejemplo

#+BEGIN_SRC
❯ cargo run --bin hola
Hola!
Alumno: Christian Markwart Höppner.
Asignatura: Fundamentos de la Informática.
Curso: CAD 2018/19.
#+END_SRC

#+BEGIN_SRC
❯ cargo run --bin numero_mayor
Hola!
Introduzca el primer número: 2
Introduzca el segundo número: 12
El número mayor es 12.
Gracias y hasta luego.
#+END_SRC

** Autoría
El contenido de este repositorio es propiedad legal de Christian Höppner, quien
lo publica con la esperanza de que resulte útil, pero sin ningún tipo de
responsabilidad o garantía.

Puede usted hacer cualquier tipo de uso, pero si lo modifica de cualquier
manera, estará obligado legalmente a compartir sus modificaciones con el
público, bajo los acuerdos de la GNU General Public License, versión 3.

** Aviso de copyright
Copyright © 2018 Christian Höppner

This file is part of the class assignment PED2 for CAD 2018/19.

PED2 is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

PED2 is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with Foobar.  If not, see <https://www.gnu.org/licenses/>.
